#nodeLinker: node-modules
defaultSemverRangePrefix: ''

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc

# fix missing package deps
packageExtensions:
  # https://github.com/davipon/esbuild-plugin-pino/issues/73
  esbuild-plugin-pino@*:
    dependencies:
      'thread-stream': '*'
